name: ExamplePlugin
version: ${project.version}
main: org.donnerlab.donnercraft.exampleplugin.ExamplePlugin
author: donnerlab
commands:
  invoice:
    description: Get Invoice with memo from server usage /invoice amt memo
    usage: /invoice
  teleport:
    description: Teleport steps forward with /teleport steps
    usage: /teleport
  sell:
    description: sell item with /sell payreq
    usage: /sell
  pay:
    description: send a payment request to a player with /pay player payreq
    usage: /pay
  listsellorders:
    description: list sellorders
    usage: /listsellorders
  getsellorder:
    description: get sellorder
    usage: /getsellorder
  claim:
    description: claim sellorder
    usage: /claim
